//чи потрібне??

//створюємо об'єктом, а не строкою

export const ENV_VARS = {
  PORT: 'PORT',
  MONGODB_USER: 'MONGODB_USER',
  MONGODB_PASSWORD: 'MONGODB_PASSWORD',
  MONGODB_DOMAIN: 'MONGODB_DOMAIN',
  MONGODB_DATABASE: 'MONGODB_DATABASE',
  //
  //
  BACKEND_DOMAIN: 'BACKEND_DOMAIN',
  //   Cloudinary
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  //
  SAVE_FILE_STRATEGY: 'SAVE_FILE_STRATEGY',
};
